name: MSBuild

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

env:
  SOLUTION_FILE_PATH: ./wuwa-moonlight.sln
  tag1: V${{ github.run_number }}
  BUILD_ID: ${{ github.run_id }}  # Уникальный идентификатор для сборки

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release, Debug]
        include:
          - configuration: Release
          - configuration: Debug

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      timeout-minutes: 10  # Увеличиваем время на случай больших сборок
      run: |
        msbuild /m /p:Configuration=${{ matrix.configuration }} ${{env.SOLUTION_FILE_PATH}}

    - name: Zip build artifacts
      run: |
        7z a bin-${{ matrix.configuration }}.zip ${{ github.workspace }}\**\bin\${{ matrix.configuration }}\*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifact-${{ matrix.configuration }}
        path: bin-${{ matrix.configuration }}.zip

  # Опциональный блок для публикации релиза (закомментирован)
  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Download a Build Artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: my-artifact
  #     - name: Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         tag_name: ${{ env.tag1 }}
  #         files: bin-${{ matrix.configuration }}-${{ env.BUILD_ID }}.zip
  #
